#!/bin/bash
clear
echo "Please make a section with the numbers 1-3"
echo
echo "1: View all the scripts that have been created in the scripts directory  "
echo "2: Display a long list of the script directory with their inode numbers "
echo "3: Display additional inode info of a specified file"
echo
read INPUT
if [ $INPUT = 1 ]
then
	cd ~/scripts
	ls  
elif [ $INPUT = 2 ]
then
	cd ~/scripts
	ls -l
elif [ $INPUT = 3 ] 
then 
	cd ~/scripts 
	echo "Enter the file you would like the inode number for"
	echo
	read FILENAME
	find ~/scripts -name $FILENAME
	ls -l $FILENAME
else
	echo "Your input was not a number 1-3, please run the script again entering a number 1-3"
fi
echo "Thank you for using this script"
