#ifndef ENTITYDEF_H
#define ENTITYDEF_H

enum {ENTITY_PLAYER, ENTITY_EXPLOSION, ENTITY_SILENT_EXPLOSION,
      ENTITY_SMALL_EXPLOSION, ENTITY_BULLET, ENTITY_PLAYER_BULLET,
      ENTITY_ENEMY_BULLET, ENTITY_ENEMY, ENTITY_ALIEN_SCOUT, ENTITY_BOSS,
      ENTITY_CHECKPOINT};

#endif
